### ISSUE TITLE
BATTLE OF RUNTEQ Vol2 レビュー

### ISSUE THREAD

**Issue by hisaju** [konjikicity/boitore#238]
サーバサイドのコードが薄いので、文脈だけは合わせておいて色々な機能を追加してサーバサイドのコードを厚くしたほうがいいかなと思います。コード自体にそれほどツッコミどころはなかったので、少しだけ気になったところを記載しますね。

-----
https://github.com/konjikicity/boitore/blob/52f9d0df501abf9aea1ce00ec61930e6c22a9d22/app/controllers/api/v1/play_results_controller.rb#L21-L24

この一連の処理がよく分からなかったのですが、同じモデルのメソッドを続けて呼ぶ必要があればモデルのメソッドにまとめたほうがいいですね。

https://github.com/konjikicity/boitore/blob/52f9d0df501abf9aea1ce00ec61930e6c22a9d22/app/controllers/admins/modes_controller.rb#L5

こちらallは不要なので、省略しちゃいましょう

**Comment by konjikicity** [comment]
@hisaju さん
お忙しい中レビューありがとうございました！！
ご指摘いただいた部分２点、モデルに移して動作本番環境でも確認できましたので
今回はセルフマージとさせていただきました！
機能的には
- Userのマイページ機能をもっと追加する
- 点数のランキング機能など
細かい機能を追加していこうかなと思います！！

重ねてですが、お忙しい中卒業生にも関わらずレビューありがとうございました！！
